language: python
env:
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy3
install:
  - "pip install ."
  - "pip install -r requirements.txt"
  - "pip install -r requirements-dev.txt"
script:
  - make test
