language: python
python:
  - "3.3"
  - "3.4"
before_install:
  - "sudo apt-get update"
  - "sudo apt-get install inkscape"
install:
  - "pip install ."
  - "pip install -r requirements.txt"
  - "pip install -r requirements-dev.txt"
script:
  - make test
